version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: master
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "skaengus2012"