codecov:
  token: ${{ secrets.CODECOV_TOKEN }}
  bot: "codecov_bot"
  require_ci_to_pass: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  branches:
    - develop
    - master